Improved indentation of ssh-tools.

diff --git a/ssh-diff b/ssh-diff
--- a/ssh-diff
+++ b/ssh-diff
@@ -14,11 +14,11 @@
 #  +---------------------------------------------------------------------------------------------------+
 
 #
-# Some colors for better output
+#  Some colors for better output
 #
 
 if [[ "$OSTYPE" == openbsd* ]]; then
-  TERM=linux    # https://github.com/rvm/rvm/issues/727
+    TERM=linux    # https://github.com/rvm/rvm/issues/727
 fi
 
   BLACK=$(tput setaf 0)
@@ -40,117 +40,117 @@ function usage() {
 
 cat << EOF
 
-  Usage: ${0##*/} [options] filename [user@]host[:filename]
+    Usage: ${0##*/} [options] filename [user@]host[:filename]
 
-  There is an extra roundtrip to the remote system
-  to check for the existence of the file to be diffed.
-  So if you are not using SSH Keys
-  you may get prompted twice for a password.
+    There is an extra roundtrip to the remote system
+    to check for the existence of the file to be diffed.
+    So if you are not using SSH Keys
+    you may get prompted twice for a password.
 
-  Diff Options:
+    Diff Options:
 
-  All options your local diff command supports ( except '-r' ).
-  See 'man diff' and 'diff --help' for more information.
+    All options your local diff command supports ( except '-r' ).
+    See 'man diff' and 'diff --help' for more information.
 
-  SSH Options:
+    SSH Options:
 
-  -4             Use IPv4 only
-  -6             Use IPv6 only
-  -p port        Port to connect to on the remote host.
-                 This can be specified on a per-host basis in the configuration file.
+        -4             Use IPv4 only
+        -6             Use IPv6 only
+        -p port        Port to connect to on the remote host.
+                       This can be specified on a per-host basis in the configuration file.
 
-  Examples:
+    Examples:
 
-  Default
+        Default:
 
-    ${0##*/} /etc/hosts 192.168.1.10
+            ${0##*/} /etc/hosts 192.168.1.10
 
-    ${0##*/} /etc/hosts root@192.168.1.10
+            ${0##*/} /etc/hosts root@192.168.1.10
 
-    ${0##*/} /etc/hosts root@192.168.1.10:/etc/hosts.old
-   
-  Side-by-Side
+            ${0##*/} /etc/hosts root@192.168.1.10:/etc/hosts.old
 
-    ${0##*/} -y /etc/hosts 192.168.1.10
+        Side-by-Side:
 
-    ${0##*/} -y /etc/hosts root@192.168.1.10
+            ${0##*/} -y /etc/hosts 192.168.1.10
 
-    ${0##*/} -y /etc/hosts root@192.168.1.10:/etc/hosts.old
+            ${0##*/} -y /etc/hosts root@192.168.1.10
 
-  Unified
+            ${0##*/} -y /etc/hosts root@192.168.1.10:/etc/hosts.old
 
-    ${0##*/} -u /etc/hosts 192.168.1.10
+        Unified:
 
-    ${0##*/} -u /etc/hosts root@192.168.1.10
+            ${0##*/} -u /etc/hosts 192.168.1.10
 
-    ${0##*/} -u /etc/hosts root@192.168.1.10:/etc/hosts.old
+            ${0##*/} -u /etc/hosts root@192.168.1.10
+
+            ${0##*/} -u /etc/hosts root@192.168.1.10:/etc/hosts.old
 
 EOF
 
 }
 
 if [[ -z $1 || $1 == "--help" ]]; then
-  usage
-  exit 1;
+    usage
+    exit 1
 fi
 
 if ! [[ $# -ge 2 ]]; then
-  echo -e "\n  ${RED}Error: Not all filenames given${RESET}" >&2
-  usage
-  exit 1
+    echo -e "\n  ${RED}Error: Not all filenames given${RESET}" >&2
+    usage
+    exit 1
 fi
 
 function supports_colordiff() {
 
-  type colordiff &> /dev/null && true || false
+    type colordiff &> /dev/null && true || false
 
 }
 
 function show_header() {
 
-  echo
-  echo "Comparing ${BOLD}$remote_host:$remote_file${RESET} (<) with ${BOLD}$local_file${RESET} (>)"
-  echo
+    echo ""
+    echo "Comparing ${BOLD}$remote_host:$remote_file${RESET} (<) with ${BOLD}$local_file${RESET} (>)"
+    echo ""
 
 }
 
 function login_successful_and_remote_file_exists() {
 
-  if [[ -z "${username}" ]]; then
-    ssh "${ssh_params[@]}" $remote_host "test -e $remote_file" &> /dev/null
-  else
-    ssh "${ssh_params[@]}" $username@$remote_host "test -e $remote_file"  &> /dev/null
-  fi
+    if [[ -z "${username}" ]]; then
+        ssh "${ssh_params[@]}" $remote_host "test -e $remote_file" &> /dev/null
+    else
+        ssh "${ssh_params[@]}" $username@$remote_host "test -e $remote_file"  &> /dev/null
+    fi
 
-  RETVAL=$?
+    RETVAL=$?
 
-  [[ ${RETVAL} -eq 255 ]] && { echo -e "\n  ${RED}Error: Could not connect to remote server${RESET}\n" >&2 ; exit ${RETVAL}; }
-  [[ ${RETVAL} -ge   1 ]] && { echo -e "\n  ${RED}Error: Remote file $remote_file not found${RESET}\n" >&2 ; exit ${RETVAL}; }
-  [[ ${RETVAL} -eq   0 ]] && true
+    [[ ${RETVAL} -eq 255 ]] && { echo -e "\n  ${RED}Error: Could not connect to remote server${RESET}\n" >&2 ; exit ${RETVAL}; }
+    [[ ${RETVAL} -ge   1 ]] && { echo -e "\n  ${RED}Error: Remote file $remote_file not found${RESET}\n" >&2 ; exit ${RETVAL}; }
+    [[ ${RETVAL} -eq   0 ]] && true
 
 }
 
 function diff_files() {
 
-  if [[ -z "${username}" ]]; then
-    if login_successful_and_remote_file_exists; then
-      show_header
-      if supports_colordiff; then
-        ssh "${ssh_params[@]}" $remote_host "cat $remote_file" | diff "${diff_params[@]}" --label "$remote_host:$remote_file" - $local_file | colordiff
-      else
-        ssh "${ssh_params[@]}" $remote_host "cat $remote_file" | diff "${diff_params[@]}" --label "$remote_host:$remote_file" - $local_file
-      fi
+    if [[ -z "${username}" ]]; then
+        if login_successful_and_remote_file_exists; then
+            show_header
+            if supports_colordiff; then
+                ssh "${ssh_params[@]}" $remote_host "cat $remote_file" | diff "${diff_params[@]}" --label "$remote_host:$remote_file" - $local_file | colordiff
+            else
+                ssh "${ssh_params[@]}" $remote_host "cat $remote_file" | diff "${diff_params[@]}" --label "$remote_host:$remote_file" - $local_file
+            fi
+        fi
+    else
+        if login_successful_and_remote_file_exists; then
+            show_header
+            if supports_colordiff; then
+                ssh "${ssh_params[@]}" $username@$remote_host "cat $remote_file"  | diff "${diff_params[@]}" --label "$remote_host:$remote_file" - $local_file | colordiff
+            else
+                ssh "${ssh_params[@]}" $username@$remote_host "cat $remote_file"  | diff "${diff_params[@]}" --label "$remote_host:$remote_file" - $local_file
+            fi
+        fi
     fi
-  else
-    if login_successful_and_remote_file_exists; then
-      show_header
-      if supports_colordiff; then
-        ssh "${ssh_params[@]}" $username@$remote_host "cat $remote_file"  | diff "${diff_params[@]}" --label "$remote_host:$remote_file" - $local_file | colordiff
-      else
-        ssh "${ssh_params[@]}" $username@$remote_host "cat $remote_file"  | diff "${diff_params[@]}" --label "$remote_host:$remote_file" - $local_file
-      fi
-    fi
-  fi
 
 }
 
@@ -162,7 +162,7 @@ function diff_files() {
 # Get all params from command line
 #
 
-params=( "$@" ) 
+params=( "$@" )
 
 #
 # Get last 2 params, store them away and remove them so only diff params are left
@@ -184,33 +184,33 @@ ssh_params_indices=()
 
 for param in ${diff_params[@]}; do
 
-  next_diff_params_index=$(( diff_params_index +1 ))
+    next_diff_params_index=$(( diff_params_index +1 ))
 
-  #
-  # find -p <port>
-  #
+    #
+    # find -p <port>
+    #
 
-  if [[ ${param} == "-p" ]] && [[ -z "${diff_params[${next_diff_params_index}]//[0-9]}" ]]; then
-    ssh_params_indices+=( ${diff_params_index} ${next_diff_params_index} )
-    ssh_params+=( ${param} ${diff_params[${next_diff_params_index}]} )
-  fi
+    if [[ ${param} == "-p" ]] && [[ -z "${diff_params[${next_diff_params_index}]//[0-9]}" ]]; then
+        ssh_params_indices+=( ${diff_params_index} ${next_diff_params_index} )
+        ssh_params+=( ${param} ${diff_params[${next_diff_params_index}]} )
+    fi
 
-  #
-  # find -4 or -6
-  #
+    #
+    # find -4 or -6
+    #
 
-  if [[ ${param} == "-4" ]] || [[ ${param} == "-6" ]]; then
-    ssh_params_indices+=( ${diff_params_index} )
-    ssh_params+=( ${param} )
-  fi
+    if [[ ${param} == "-4" ]] || [[ ${param} == "-6" ]]; then
+        ssh_params_indices+=( ${diff_params_index} )
+        ssh_params+=( ${param} )
+    fi
 
-  diff_params_index=$(( diff_params_index +1 ))
+    diff_params_index=$(( diff_params_index +1 ))
 
 done
 
 for ssh_param in ${ssh_params_indices[@]}; do
 
-  unset diff_params[$ssh_param]
+    unset diff_params[$ssh_param]
 
 done
 
@@ -223,37 +223,37 @@ done
 #
 
 if [[ $remote_params == *"@"* ]]; then
-  remote_part=$( echo ${remote_params##*@} )
-  username=$( echo ${remote_params%%@*} )
+    remote_part=$( echo ${remote_params##*@} )
+    username=$( echo ${remote_params%%@*} )
 else
-  remote_part=${remote_params}
+    remote_part=${remote_params}
 fi
 
 if [[ $remote_part == *":"* ]]; then
-  remote_file=$( echo ${remote_part##*:} )
-  remote_host=$( echo ${remote_part%%:*} )
+    remote_file=$( echo ${remote_part##*:} )
+    remote_host=$( echo ${remote_part%%:*} )
 else
-  remote_host=${remote_part}
+    remote_host=${remote_part}
 fi
 
-local_file=`readlink -f $local_filename` # get absolute path to file in case it was relative
+local_file=$(readlink -f $local_filename) # get absolute path to file in case it was relative
 
 if [[ -z "$local_file" ]]; then
-  echo -e "\n  ${RED}Error: Given file not found${RESET}\n" >&2
-  exit 1
+    echo -e "\n  ${RED}Error: Given file not found${RESET}\n" >&2
+    exit 1
 fi
 
 if [[ ! -f $local_file ]]; then
-  echo -e "\n  ${RED}Error: Local file $local_file not found${RESET}\n" >&2
-  exit 1
+    echo -e "\n  ${RED}Error: Local file $local_file not found${RESET}\n" >&2
+    exit 1
 fi
 
 if [[ -z "$remote_file" ]]; then
-  remote_file=$local_file
+    remote_file=$local_file
 fi
 
 #
-# Finally diff them !
+# Finally diff them!
 #
 
 diff_files
diff --git a/ssh-ping b/ssh-ping
--- a/ssh-ping
+++ b/ssh-ping
@@ -24,7 +24,7 @@ trap print_statistics SIGINT
 #
 
 if [[ "$OSTYPE" == openbsd* ]]; then
-  TERM=linux    # https://github.com/rvm/rvm/issues/727
+    TERM=linux # https://github.com/rvm/rvm/issues/727
 fi
 
   BLACK=$(tput setaf 0)
@@ -76,88 +76,87 @@ function usage() {
 
 cat << EOF
 
-  Usage: ${0##*/} options [user@]host
+    Usage: ${0##*/} options [user@]host
 
-  OPTIONS:
-
-  -4             Use IPv4 only
-  -6             Use IPv6 only
-  -c count       Stop after sending <count> request packets
-  -F configfile  Specifies an alternative per-user configuration file.
-                 If a configuration file is given on the command line,
-                 the system-wide configuration file ( /etc/ssh/ssh_config ) will be ignored.
-                 The default for the per-user configuration file is ~/.ssh/config.
-  -h             Show this message
-  -i interval    Wait <interval> seconds between sending each request.
-                 The default is 1 second.
-  -l user        Try login with <user> as username. The default is \$USER.
-  -D             Print timestamp (unix time + microseconds as in gettimeofday) before each line
-  -W timeout     Time to wait for a response, in seconds
-  -p port        Port to connect to on the remote host.
-                 This can be specified on a per-host basis in the configuration file.
-  -q             Quiet output.
-                 Nothing is displayed except the summary lines at startup time and when finished
-  -v             Verbose output
+    OPTIONS:
+        -4             Use IPv4 only
+        -6             Use IPv6 only
+        -c count       Stop after sending <count> request packets
+        -F configfile  Specifies an alternative per-user configuration file.
+                       If a configuration file is given on the command line,
+                       the system-wide configuration file ( /etc/ssh/ssh_config ) will be ignored.
+                       The default for the per-user configuration file is ~/.ssh/config.
+        -h             Show this message
+        -i interval    Wait <interval> seconds between sending each request.
+                       The default is 1 second.
+        -l user        Try login with <user> as username. The default is \$USER.
+        -D             Print timestamp (unix time + microseconds as in gettimeofday) before each line
+        -W timeout     Time to wait for a response, in seconds
+        -p port        Port to connect to on the remote host.
+                       This can be specified on a per-host basis in the configuration file.
+        -q             Quiet output.
+                       Nothing is displayed except the summary lines at startup time and when finished
+        -v             Verbose output
 
 EOF
 
 }
 
 if [[ -z $1 || $1 == "--help" ]]; then
-  usage
-  exit 1;
+    usage
+    exit 1;
 fi
 
 function command_exists() {
 
-  command -v ${1} >/dev/null 2>&1
+    command -v ${1} >/dev/null 2>&1
 
 }
 
 function get_timestamp() {
 
-  if [[ "$OSTYPE" == "linux-gnu" ]]; then
-    date +%s.%6N
-  else
-    command_exists python && python -c 'import time; ms = time.time() ; print "%.6f" % ms'
-  fi
+    if [[ "$OSTYPE" == "linux-gnu" ]]; then
+        date +%s.%6N
+    else
+        command_exists python && python -c 'import time; ms = time.time() ; print "%.6f" % ms'
+    fi
 
 }
 
 function get_request_timestamp() {
 
-  if [[ "$OSTYPE" == "linux-gnu" ]]; then
-    date +%s%3N
-  else
-    command_exists python && python -c 'import time; ms = int(round(time.time() * 1000)) ; print ms'
-  fi
+    if [[ "$OSTYPE" == "linux-gnu" ]]; then
+        date +%s%3N
+    else
+        command_exists python && python -c 'import time; ms = int(round(time.time() * 1000)) ; print ms'
+    fi
 
 }
 
 function print_statistics() {
 
-  [[ $requests_transmitted -eq 0 ]] && exit
+    [[ $requests_transmitted -eq 0 ]] && exit
 
-  requests_loss=$(( 100 * requests_lost / requests_transmitted ))
+    requests_loss=$(( 100 * requests_lost / requests_transmitted ))
 
-  echo
-  echo "${WHITE}---${RESET} ${YELLOW}$host${RESET} ${WHITE}ping statistics${RESET} ${WHITE}---${RESET}"
+    echo ""
+    echo "${WHITE}---${RESET} ${YELLOW}$host${RESET} ${WHITE}ping statistics${RESET} ${WHITE}---${RESET}"
 
-  statistics_ok="${GREEN}$requests_transmitted${RESET} ${WHITE}requests transmitted${RESET}, "
-  statistics_ok+="${GREEN}$requests_received${RESET} ${WHITE}requests received${RESET}, "
-  statistics_ok+="${GREEN}$requests_loss%${RESET} ${WHITE}request loss${RESET}"
+    statistics_ok="${GREEN}$requests_transmitted${RESET} ${WHITE}requests transmitted${RESET}, "
+    statistics_ok+="${GREEN}$requests_received${RESET} ${WHITE}requests received${RESET}, "
+    statistics_ok+="${GREEN}$requests_loss%${RESET} ${WHITE}request loss${RESET}"
 
-  statistics_warn="${YELLOW}$requests_transmitted${RESET} ${WHITE}requests transmitted${RESET}, "
-  statistics_warn+="${YELLOW}$requests_received${RESET} ${WHITE}requests received${RESET}, "
-  statistics_warn+="${YELLOW}$requests_loss%${RESET} ${WHITE}request loss${RESET}"
+    statistics_warn="${YELLOW}$requests_transmitted${RESET} ${WHITE}requests transmitted${RESET}, "
+    statistics_warn+="${YELLOW}$requests_received${RESET} ${WHITE}requests received${RESET}, "
+    statistics_warn+="${YELLOW}$requests_loss%${RESET} ${WHITE}request loss${RESET}"
 
-  statistics_crit="${RED}$requests_transmitted${RESET} ${WHITE}requests transmitted${RESET}, "
-  statistics_crit+="${RED}$requests_received${RESET} ${WHITE}requests received${RESET}, "
-  statistics_crit+="${RED}$requests_loss%${RESET} ${WHITE}request loss${RESET}"
+    statistics_crit="${RED}$requests_transmitted${RESET} ${WHITE}requests transmitted${RESET}, "
+    statistics_crit+="${RED}$requests_received${RESET} ${WHITE}requests received${RESET}, "
+    statistics_crit+="${RED}$requests_loss%${RESET} ${WHITE}request loss${RESET}"
 
-  [[ $requests_loss -eq 100 ]] &&  echo "$statistics_crit" && exit
-  [[ $requests_loss -gt   1 ]] &&  echo "$statistics_warn" && exit
-  [[ $requests_loss -eq   0 ]] &&  echo "$statistics_ok"   && exit
+    [[ $requests_loss -eq 100 ]] &&  echo "$statistics_crit" && exit
+    [[ $requests_loss -gt   1 ]] &&  echo "$statistics_warn" && exit
+    [[ $requests_loss -eq   0 ]] &&  echo "$statistics_ok"   && exit
 
 }
 
@@ -166,51 +165,51 @@ function print_statistics() {
 #
 
 while getopts ":46c:F:hi:l:Dp:vW:q" opt; do
-  case ${opt} in
-     4 )
-       SSH_FLAGS+=("-4")
-       ;;
-     6 )
-       SSH_FLAGS+=("-6")
-       ;;
-     c )
-       [[ $OPTARG =~ ^[0-9]+$ ]] && ping_count=$OPTARG
-       ;;
-     F )
-       SSH_FLAGS+=("-F")
-       SSH_FLAGS+=("$OPTARG")
-       ;;
-     h )
-       usage
-       exit 1
-       ;;
-     i )
-       ping_interval=$OPTARG
-       ;;
-     l )
-       SSH_FLAGS+=("-l") && SSH_FLAGS+=("$OPTARG")
-       ;;
-     D )
-       print_timestamp="yes"
-       ;;
-     p )
-       [[ $OPTARG =~ ^[0-9]+$ ]] && SSH_FLAGS+=("-p") && SSH_FLAGS+=("$OPTARG")
-       ;;
-     v )
-       verbose="yes"
-       ;;
-     W )
-       [[ $OPTARG =~ ^[0-9]+$ ]] && connect_timeout=$OPTARG
-       ;;
-     q )
-       quiet="yes"
-       ;;
-    \? )
-       echo "Invalid option: $OPTARG" 1>&2
-       usage
-       exit 1
-      ;;
-  esac
+    case ${opt} in
+        4 )
+            SSH_FLAGS+=("-4")
+        ;;
+        6 )
+            SSH_FLAGS+=("-6")
+        ;;
+        c )
+            [[ $OPTARG =~ ^[0-9]+$ ]] && ping_count=$OPTARG
+        ;;
+        F )
+            SSH_FLAGS+=("-F")
+            SSH_FLAGS+=("$OPTARG")
+        ;;
+        h )
+            usage
+            exit 1
+        ;;
+        i )
+            ping_interval=$OPTARG
+        ;;
+        l )
+            SSH_FLAGS+=("-l") && SSH_FLAGS+=("$OPTARG")
+        ;;
+        D )
+            print_timestamp="yes"
+        ;;
+        p )
+            [[ $OPTARG =~ ^[0-9]+$ ]] && SSH_FLAGS+=("-p") && SSH_FLAGS+=("$OPTARG")
+        ;;
+        v )
+            verbose="yes"
+        ;;
+        W )
+            [[ $OPTARG =~ ^[0-9]+$ ]] && connect_timeout=$OPTARG
+        ;;
+        q )
+            quiet="yes"
+        ;;
+        \? )
+            echo "Invalid option: $OPTARG" 1>&2
+            usage
+            exit 1
+        ;;
+    esac
 done
 
 shift $((OPTIND - 1))
@@ -228,10 +227,10 @@ SSH_OPTS+=( -o ConnectTimeout=$connect_timeout )
 #
 
 if [[ $1 == *"@"* ]]; then
-  host=$( echo ${1##*@} )
-  username=$( echo ${1%%@*} )
+    host=$( echo ${1##*@} )
+    username=$( echo ${1%%@*} )
 else
-  host=${1}
+    host=${1}
 fi
 
 [[ -z "${host}" ]] && { echo -e "\n  ${RED}Error: No target host given${RESET}" ; usage; exit 1; }
@@ -243,69 +242,68 @@ fi
 echo "${BOLD}SSHPING${RESET} ${YELLOW}${host}${RESET}"
 
 if [[ ${verbose} == yes ]]; then
-  echo -n "${BLUE}"
-  echo "SSH_FLAGS: ${SSH_FLAGS[@]}"
-  echo "SSH_OPTS: ${SSH_OPTS[@]}"
-  echo -n "${RESET}"
+    echo -n "${BLUE}"
+    echo "SSH_FLAGS: ${SSH_FLAGS[@]}"
+    echo "SSH_OPTS: ${SSH_OPTS[@]}"
+    echo -n "${RESET}"
 fi
 
 command_exists python || echo "${YELLOW}WARNING:${RESET} No python found. Unable to measure time (${WHITE}time${RESET}=${RED}0${RESET} ms)" >&2
 
 while true; do
 
-  #
-  # ping only $count times or forever if $count = 0
-  #
+    #
+    # ping only $count times or forever if $count = 0
+    #
 
-  [[ ${ping_count} -gt 0 ]] && [[ ${ssh_seq} -gt ${ping_count} ]] && break
+    [[ ${ping_count} -gt 0 ]] && [[ ${ssh_seq} -gt ${ping_count} ]] && break
 
-  #
-  # unix time + microseconds as in gettimeofday - used for -D option
-  #
+    #
+    # unix time + microseconds as in gettimeofday - used for -D option
+    #
 
-  timestamp=$( get_timestamp )
+    timestamp=$( get_timestamp )
 
-  #
-  # Doing the actual request and measure its execution time
-  #
+    #
+    # Doing the actual request and measure its execution time
+    #
 
-  start_request=$( get_request_timestamp )
+    start_request=$( get_request_timestamp )
 
-  if [[ -z "${username}" ]]; then
-    status=$(ssh "${SSH_FLAGS[@]}" "${SSH_OPTS[@]}" "${host}" echo pong 2>&1 | grep -oE 'pong|denied|sftp')
-  else
-    status=$(ssh "${SSH_FLAGS[@]}" "${SSH_OPTS[@]}" "${username}@${host}" echo pong 2>&1 | grep -oE 'pong|denied|sftp')
-  fi
+    if [[ -z "${username}" ]]; then
+        status=$(ssh "${SSH_FLAGS[@]}" "${SSH_OPTS[@]}" "${host}" echo pong 2>&1 | grep -oE 'pong|denied|sftp')
+    else
+        status=$(ssh "${SSH_FLAGS[@]}" "${SSH_OPTS[@]}" "${username}@${host}" echo pong 2>&1 | grep -oE 'pong|denied|sftp')
+    fi
 
-  end_request=$( get_request_timestamp )
+    end_request=$( get_request_timestamp )
+    time_request=$((end_request-start_request))
 
-  time_request=$((end_request-start_request))
+    #
+    # Output "Pong"  if request succeeded by login in and echoing back our string
+    # Output "Reply" if the SSH server is at least talking to us but login was denied
+    #
 
-  #
-  # Output "Pong"  if request succeeded by login in and echoing back our string
-  # Output "Reply" if the SSH server is at least talking to us but login was denied
-  #
+    if [[ $status == pong ]]; then
+        requests_received=$(( requests_received + 1 ))
+        [[ ${quiet} == no ]] && [[ ${print_timestamp} == yes ]] && echo -n "${WHITE}[${RESET}${MAGENTA}${timestamp}${RESET}${WHITE}]${RESET} "
+        [[ ${quiet} == no ]] && echo "${GREEN}Pong${RESET} ${WHITE}from${RESET} ${YELLOW}${host}${RESET}${WHITE}: ssh_seq${RESET}=${RED}${ssh_seq}${RESET} ${WHITE}time${RESET}=${RED}${time_request}${RESET} ms"
+    elif [[ $status == denied || $status == sftp ]]; then
+        requests_received=$(( requests_received + 1 ))
+        [[ ${quiet} == no ]] && [[ ${print_timestamp} == yes ]] && echo -n "${WHITE}[${RESET}${MAGENTA}${timestamp}${RESET}${WHITE}]${RESET} "
+        [[ ${quiet} == no ]] && echo "${CYAN}Reply${RESET} ${WHITE}from${RESET} ${YELLOW}${host}${RESET}${WHITE}: ssh_seq${RESET}=${RED}${ssh_seq}${RESET} ${WHITE}time${RESET}=${RED}${time_request}${RESET} ms"
+    else
+        requests_lost=$(( requests_lost + 1 ))
+    fi
 
-  if [[ $status == pong ]]; then
-    requests_received=$(( requests_received + 1 ))
-    [[ ${quiet} == no ]] && [[ ${print_timestamp} == yes ]] && echo -n "${WHITE}[${RESET}${MAGENTA}${timestamp}${RESET}${WHITE}]${RESET} "
-    [[ ${quiet} == no ]] && echo "${GREEN}Pong${RESET} ${WHITE}from${RESET} ${YELLOW}${host}${RESET}${WHITE}: ssh_seq${RESET}=${RED}${ssh_seq}${RESET} ${WHITE}time${RESET}=${RED}${time_request}${RESET} ms"
-  elif [[ $status == denied || $status == sftp ]]; then
-    requests_received=$(( requests_received + 1 ))
-    [[ ${quiet} == no ]] && [[ ${print_timestamp} == yes ]] && echo -n "${WHITE}[${RESET}${MAGENTA}${timestamp}${RESET}${WHITE}]${RESET} "
-    [[ ${quiet} == no ]] && echo "${CYAN}Reply${RESET} ${WHITE}from${RESET} ${YELLOW}${host}${RESET}${WHITE}: ssh_seq${RESET}=${RED}${ssh_seq}${RESET} ${WHITE}time${RESET}=${RED}${time_request}${RESET} ms"
-  else
-    requests_lost=$(( requests_lost + 1 ))
-  fi
+    requests_transmitted=$ssh_seq
+    ssh_seq=$(( ssh_seq + 1 ))
 
-  requests_transmitted=$ssh_seq
-  ssh_seq=$(( ssh_seq + 1))
+    #
+    # Don't sleep if we do just 1 request
+    #
 
-  #
-  # Don't sleep if we do just 1 request
-  #
-
-  [[ ${ping_count} -eq 1 ]] || sleep ${ping_interval}
+    [[ ${ping_count} -eq 1 ]] || sleep ${ping_interval}
 
 done
 
