Check for perl only on Non-GNU Linux Systems

diff --git a/ssh-ping b/ssh-ping
--- a/ssh-ping
+++ b/ssh-ping
@@ -253,7 +253,9 @@ if [[ ${verbose} == yes ]]; then
     echo -e -n "${RESET}"
 fi
 
-command_exists perl || echo -e "${YELLOW}WARNING:${RESET} No perl found, time measure probably fails (${WHITE}time${RESET}=${RED}0${RESET} ms)" >&2
+if [[ ! "$OSTYPE" == "linux-gnu" ]]; then
+  command_exists perl || echo -e "${YELLOW}WARNING:${RESET} No perl found, time measure probably fails (${WHITE}time${RESET}=${RED}0${RESET} ms)" >&2
+fi
 
 while true; do
 
