[shellcheck] Remove optional errors
SC2250: Prefer putting braces around variable references even when not strictly required.

https://www.shellcheck.net/wiki/SC2250

diff --git a/ssh-diff b/ssh-diff
--- a/ssh-diff
+++ b/ssh-diff
@@ -100,7 +100,7 @@ function supports_colordiff() {
 function show_header() {
 
     echo ""
-    echo -e "Comparing ${BOLD}$remote_host:$remote_file${RESET} (<) with ${BOLD}$local_file${RESET} (>)"
+    echo -e "Comparing ${BOLD}${remote_host}:${remote_file}${RESET} (<) with ${BOLD}${local_file}${RESET} (>)"
     echo ""
 
 }
@@ -113,15 +113,15 @@ function login_successful_and_remote_file_exists() {
     fi
 
     if [[ -z "${username}" ]]; then
-        ssh "${ssh_params[@]}" $remote_host "test -e $remote_file" &> /dev/null
+        ssh "${ssh_params[@]}" ${remote_host} "test -e ${remote_file}" &> /dev/null
     else
-        ssh "${ssh_params[@]}" $username@$remote_host "test -e $remote_file" &> /dev/null
+        ssh "${ssh_params[@]}" ${username}@${remote_host} "test -e ${remote_file}" &> /dev/null
     fi
 
     RETVAL=$?
 
     [[ ${RETVAL} -eq 255 ]] && { echo -e "\n  ${RED}Error: Could not connect to remote server${RESET}\n" >&2 ; exit ${RETVAL}; }
-    [[ ${RETVAL} -ge   1 ]] && { echo -e "\n  ${RED}Error: Remote file $remote_file not found${RESET}\n" >&2 ; exit ${RETVAL}; }
+    [[ ${RETVAL} -ge   1 ]] && { echo -e "\n  ${RED}Error: Remote file ${remote_file} not found${RESET}\n" >&2 ; exit ${RETVAL}; }
     [[ ${RETVAL} -eq   0 ]] && true
 
 }
@@ -132,7 +132,7 @@ function diff_files() {
         if login_successful_and_remote_file_exists; then
             show_header
             if supports_colordiff; then
-                ssh "${ssh_params[@]}" $remote_host "cat $remote_file" | diff "${diff_params[@]}" --label "$remote_host:$remote_file" - $local_file | colordiff
+                ssh "${ssh_params[@]}" ${remote_host} "cat ${remote_file}" | diff "${diff_params[@]}" --label "${remote_host}:${remote_file}" - ${local_file} | colordiff
             else
                 # Pipe the output to cat after diffing
                 #
@@ -140,14 +140,14 @@ function diff_files() {
                 # Reason is that a normal diff returns with 1
                 # when files differ but colordiff changes the return code to 0.
 
-                ssh "${ssh_params[@]}" $remote_host "cat $remote_file" | diff "${diff_params[@]}" --label "$remote_host:$remote_file" - $local_file | cat
+                ssh "${ssh_params[@]}" ${remote_host} "cat ${remote_file}" | diff "${diff_params[@]}" --label "${remote_host}:${remote_file}" - ${local_file} | cat
             fi
         fi
     else
         if login_successful_and_remote_file_exists; then
             show_header
             if supports_colordiff; then
-                ssh "${ssh_params[@]}" $username@$remote_host "cat $remote_file"  | diff "${diff_params[@]}" --label "$remote_host:$remote_file" - $local_file | colordiff
+                ssh "${ssh_params[@]}" ${username}@${remote_host} "cat ${remote_file}"  | diff "${diff_params[@]}" --label "${remote_host}:${remote_file}" - ${local_file} | colordiff
             else
                 # Pipe the output to cat after diffing
                 #
@@ -155,7 +155,7 @@ function diff_files() {
                 # Reason is that a normal diff returns with 1
                 # when files differ but colordiff changes the return code to 0.
 
-                ssh "${ssh_params[@]}" $username@$remote_host "cat $remote_file"  | diff "${diff_params[@]}" --label "$remote_host:$remote_file" - $local_file | cat
+                ssh "${ssh_params[@]}" ${username}@${remote_host} "cat ${remote_file}"  | diff "${diff_params[@]}" --label "${remote_host}:${remote_file}" - ${local_file} | cat
             fi
         fi
     fi
@@ -231,34 +231,34 @@ done
 #                    -> filename gets stored in $remote_file
 #
 
-if [[ $remote_params == *"@"* ]]; then
+if [[ ${remote_params} == *"@"* ]]; then
     remote_part=$( echo ${remote_params##*@} )
     username=$( echo ${remote_params%%@*} )
 else
     remote_part=${remote_params}
 fi
 
-if [[ $remote_part == *":"* ]]; then
+if [[ ${remote_part} == *":"* ]]; then
     remote_file=$( echo ${remote_part##*:} )
     remote_host=$( echo ${remote_part%%:*} )
 else
     remote_host=${remote_part}
 fi
 
-local_file=$(readlink -f $local_filename) # get absolute path to file in case it was relative
+local_file=$(readlink -f ${local_filename}) # get absolute path to file in case it was relative
 
-if [[ -z "$local_file" ]]; then
+if [[ -z "${local_file}" ]]; then
     echo -e "\n  ${RED}Error: Given file not found${RESET}\n" >&2
     exit 1
 fi
 
-if [[ ! -f $local_file ]]; then
-    echo -e "\n  ${RED}Error: Local file $local_file not found${RESET}\n" >&2
+if [[ ! -f ${local_file} ]]; then
+    echo -e "\n  ${RED}Error: Local file ${local_file} not found${RESET}\n" >&2
     exit 1
 fi
 
-if [[ -z "$remote_file" ]]; then
-    remote_file=$local_file
+if [[ -z "${remote_file}" ]]; then
+    remote_file=${local_file}
 fi
 
 #
diff --git a/ssh-hostkeys b/ssh-hostkeys
--- a/ssh-hostkeys
+++ b/ssh-hostkeys
@@ -57,13 +57,13 @@ while getopts ":46hp:T:" opt; do
             exit 1
         ;;
         p )
-            [[ $OPTARG =~ ^[0-9]+$ ]] && SSH_FLAGS+=("-p") && SSH_FLAGS+=("$OPTARG")
+            [[ ${OPTARG} =~ ^[0-9]+$ ]] && SSH_FLAGS+=("-p") && SSH_FLAGS+=("${OPTARG}")
         ;;
         T )
-            SSH_FLAGS+=("-T") && SSH_FLAGS+=("$OPTARG")
+            SSH_FLAGS+=("-T") && SSH_FLAGS+=("${OPTARG}")
         ;;
         \? )
-            echo "Invalid option: $OPTARG" 1>&2
+            echo "Invalid option: ${OPTARG}" 1>&2
             usage
             exit 1
         ;;
@@ -77,7 +77,7 @@ remote_host=$1
 the_hostkeys=$( mktemp /tmp/ssh-hostkeys.XXXXXX )
 trap 'rm -f $the_hostkeys' EXIT
 
-ssh-keyscan "${SSH_FLAGS[@]}" $remote_host > $the_hostkeys 2>/dev/null
+ssh-keyscan "${SSH_FLAGS[@]}" ${remote_host} > ${the_hostkeys} 2>/dev/null
 
 fingerprint_hashes=( md5 sha256 )
 
@@ -85,9 +85,9 @@ function get_fingerprints () {
 
   hash_type=$1
 
-  ssh-keygen -E $hash_type -qlf $the_hostkeys | while IFS= read -r line; do
+  ssh-keygen -E ${hash_type} -qlf ${the_hostkeys} | while IFS= read -r line; do
 
-    key_data=( $(printf '%s\n' "$line") )
+    key_data=( $(printf '%s\n' "${line}") )
     key_size=${key_data[0]}
     key_hash=${key_data[1]}
     #key_remote_host=${key_data[2]}
@@ -95,7 +95,7 @@ function get_fingerprints () {
     key_hash_type="${key_hash%%:*}"
     key_hash_data="${key_hash#*:}"
 
-    printf "%10s%6s%8s %s\n" $key_type $key_size $key_hash_type $key_hash_data
+    printf "%10s%6s%8s %s\n" ${key_type} ${key_size} ${key_hash_type} ${key_hash_data}
 
   done
 
@@ -103,6 +103,6 @@ function get_fingerprints () {
 
 for fingerprint_hash in "${fingerprint_hashes[@]}"; do
 
-  get_fingerprints $fingerprint_hash
+  get_fingerprints ${fingerprint_hash}
 
 done | sort
diff --git a/ssh-ping b/ssh-ping
--- a/ssh-ping
+++ b/ssh-ping
@@ -112,10 +112,10 @@ function command_exists() {
 
 function get_timestamp() {
 
-    if [[ "$print_timestamp_human_readable" == "yes" ]]; then
+    if [[ "${print_timestamp_human_readable}" == "yes" ]]; then
       date
     else
-      if [[ "$OSTYPE" == "linux-gnu" ]]; then
+      if [[ "${OSTYPE}" == "linux-gnu" ]]; then
         date +%s.%6N
       else
         command_exists perl && perl -MTime::HiRes=time -e 'printf "%.6f", time'
@@ -126,7 +126,7 @@ function get_timestamp() {
 
 function get_request_timestamp() {
 
-    if [[ "$OSTYPE" == "linux-gnu" ]]; then
+    if [[ "${OSTYPE}" == "linux-gnu" ]]; then
         date +%s%3N
     else
         command_exists perl && perl -MTime::HiRes=time -e 'printf "%i", time * 1000'
@@ -136,28 +136,28 @@ function get_request_timestamp() {
 
 function print_statistics() {
 
-    [[ $requests_transmitted -eq 0 ]] && exit
+    [[ ${requests_transmitted} -eq 0 ]] && exit
 
     requests_loss=$(( 100 * requests_lost / requests_transmitted ))
 
     echo ""
-    echo -e "${WHITE}---${RESET} ${YELLOW}$host${RESET} ${WHITE}ping statistics${RESET} ${WHITE}---${RESET}"
+    echo -e "${WHITE}---${RESET} ${YELLOW}${host}${RESET} ${WHITE}ping statistics${RESET} ${WHITE}---${RESET}"
 
-    statistics_ok="${GREEN}$requests_transmitted${RESET} ${WHITE}requests transmitted${RESET}, "
-    statistics_ok+="${GREEN}$requests_received${RESET} ${WHITE}requests received${RESET}, "
-    statistics_ok+="${GREEN}$requests_loss%${RESET} ${WHITE}request loss${RESET}"
+    statistics_ok="${GREEN}${requests_transmitted}${RESET} ${WHITE}requests transmitted${RESET}, "
+    statistics_ok+="${GREEN}${requests_received}${RESET} ${WHITE}requests received${RESET}, "
+    statistics_ok+="${GREEN}${requests_loss}%${RESET} ${WHITE}request loss${RESET}"
 
-    statistics_warn="${YELLOW}$requests_transmitted${RESET} ${WHITE}requests transmitted${RESET}, "
-    statistics_warn+="${YELLOW}$requests_received${RESET} ${WHITE}requests received${RESET}, "
-    statistics_warn+="${YELLOW}$requests_loss%${RESET} ${WHITE}request loss${RESET}"
+    statistics_warn="${YELLOW}${requests_transmitted}${RESET} ${WHITE}requests transmitted${RESET}, "
+    statistics_warn+="${YELLOW}${requests_received}${RESET} ${WHITE}requests received${RESET}, "
+    statistics_warn+="${YELLOW}${requests_loss}%${RESET} ${WHITE}request loss${RESET}"
 
-    statistics_crit="${RED}$requests_transmitted${RESET} ${WHITE}requests transmitted${RESET}, "
-    statistics_crit+="${RED}$requests_received${RESET} ${WHITE}requests received${RESET}, "
-    statistics_crit+="${RED}$requests_loss%${RESET} ${WHITE}request loss${RESET}"
+    statistics_crit="${RED}${requests_transmitted}${RESET} ${WHITE}requests transmitted${RESET}, "
+    statistics_crit+="${RED}${requests_received}${RESET} ${WHITE}requests received${RESET}, "
+    statistics_crit+="${RED}${requests_loss}%${RESET} ${WHITE}request loss${RESET}"
 
-    [[ $requests_loss -eq 100 ]] &&  echo -e "$statistics_crit" && exit
-    [[ $requests_loss -gt   1 ]] &&  echo -e "$statistics_warn" && exit
-    [[ $requests_loss -eq   0 ]] &&  echo -e "$statistics_ok"   && exit
+    [[ ${requests_loss} -eq 100 ]] &&  echo -e "${statistics_crit}" && exit
+    [[ ${requests_loss} -gt   1 ]] &&  echo -e "${statistics_warn}" && exit
+    [[ ${requests_loss} -eq   0 ]] &&  echo -e "${statistics_ok}"   && exit
 
 }
 
@@ -174,21 +174,21 @@ while getopts ":46c:F:hi:l:DHp:vW:q" opt; do
             SSH_FLAGS+=("-6")
         ;;
         c )
-            [[ $OPTARG =~ ^[0-9]+$ ]] && ping_count=$OPTARG
+            [[ ${OPTARG} =~ ^[0-9]+$ ]] && ping_count=${OPTARG}
         ;;
         F )
             SSH_FLAGS+=("-F")
-            SSH_FLAGS+=("$OPTARG")
+            SSH_FLAGS+=("${OPTARG}")
         ;;
         h )
             usage
             exit 1
         ;;
         i )
-            ping_interval=$OPTARG
+            ping_interval=${OPTARG}
         ;;
         l )
-            SSH_FLAGS+=("-l") && SSH_FLAGS+=("$OPTARG")
+            SSH_FLAGS+=("-l") && SSH_FLAGS+=("${OPTARG}")
         ;;
         D )
             print_timestamp="yes"
@@ -198,19 +198,19 @@ while getopts ":46c:F:hi:l:DHp:vW:q" opt; do
             print_timestamp_human_readable="yes"
         ;;
         p )
-            [[ $OPTARG =~ ^[0-9]+$ ]] && SSH_FLAGS+=("-p") && SSH_FLAGS+=("$OPTARG")
+            [[ ${OPTARG} =~ ^[0-9]+$ ]] && SSH_FLAGS+=("-p") && SSH_FLAGS+=("${OPTARG}")
         ;;
         v )
             verbose="yes"
         ;;
         W )
-            [[ $OPTARG =~ ^[0-9]+$ ]] && connect_timeout=$OPTARG
+            [[ ${OPTARG} =~ ^[0-9]+$ ]] && connect_timeout=${OPTARG}
         ;;
         q )
             quiet="yes"
         ;;
         \? )
-            echo "Invalid option: $OPTARG" 1>&2
+            echo "Invalid option: ${OPTARG}" 1>&2
             usage
             exit 1
         ;;
@@ -219,7 +219,7 @@ done
 
 shift $((OPTIND - 1))
 
-SSH_OPTS+=( -o ConnectTimeout=$connect_timeout )
+SSH_OPTS+=( -o ConnectTimeout=${connect_timeout} )
 
 #
 # Getting username and host from command line without using grep and awk
@@ -253,7 +253,7 @@ if [[ ${verbose} == yes ]]; then
     echo -e -n "${RESET}"
 fi
 
-if [[ ! "$OSTYPE" == "linux-gnu" ]]; then
+if [[ ! "${OSTYPE}" == "linux-gnu" ]]; then
   command_exists perl || echo -e "${YELLOW}WARNING:${RESET} No perl found, time measure probably fails (${WHITE}time${RESET}=${RED}0${RESET} ms)" >&2
 fi
 
@@ -291,11 +291,11 @@ while true; do
     # Output "Reply" if the SSH server is at least talking to us but login was denied
     #
 
-    if [[ $status == pong ]]; then
+    if [[ ${status} == pong ]]; then
         requests_received=$(( requests_received + 1 ))
         [[ ${quiet} == no ]] && [[ ${print_timestamp} == yes ]] && echo -e -n "${WHITE}[${RESET}${MAGENTA}${timestamp}${RESET}${WHITE}]${RESET} "
         [[ ${quiet} == no ]] && echo -e "${GREEN}Pong${RESET} ${WHITE}from${RESET} ${YELLOW}${host}${RESET}${WHITE}: ssh_seq${RESET}=${RED}${ssh_seq}${RESET} ${WHITE}time${RESET}=${RED}${time_request}${RESET} ms"
-    elif [[ $status == denied || $status == sftp ]]; then
+    elif [[ ${status} == denied || ${status} == sftp ]]; then
         requests_received=$(( requests_received + 1 ))
         [[ ${quiet} == no ]] && [[ ${print_timestamp} == yes ]] && echo -e -n "${WHITE}[${RESET}${MAGENTA}${timestamp}${RESET}${WHITE}]${RESET} "
         [[ ${quiet} == no ]] && echo -e "${CYAN}Reply${RESET} ${WHITE}from${RESET} ${YELLOW}${host}${RESET}${WHITE}: ssh_seq${RESET}=${RED}${ssh_seq}${RESET} ${WHITE}time${RESET}=${RED}${time_request}${RESET} ms"
@@ -303,7 +303,7 @@ while true; do
         requests_lost=$(( requests_lost + 1 ))
     fi
 
-    requests_transmitted=$ssh_seq
+    requests_transmitted=${ssh_seq}
     ssh_seq=$(( ssh_seq + 1 ))
 
     #
